- hosts: all
  tasks:
##DISABLE  - name: Testing Augeas dicts
##DISABLE    augeas:
##DISABLE      commands:
##DISABLE        defvar:
##DISABLE          conf: '/file/etc/httpd/conf.d/owncloud.conf'
##DISABLE        load: 
##DISABLE        defvar: 
##DISABLE          ocloud_dir: '$conf/Directory[arg="/usr/share/owncloud/"]'
##DISABLE        touch: '$ocloud_dir/directive[last()+1]'
##DISABLE        defvar:
##DISABLE          last_stmt: '$ocloud_dir/directive[last()]'
##DISABLE        set: 
##DISABLE          node: '$last_stmt'
##DISABLE          label: Require
##DISABLE        set:
##DISABLE          node: '$last_stmt/arg[1]'
##DISABLE          label: all
##DISABLE        set:
##DISABLE          node: '$last_stmt/arg[2]'
##DISABLE          label: granted
##DISABLE        save:
##DISABLE      augdebug: /tmp/aug.log
##DISABLE
  - name: Testing Augeas lists
    augeas:
      commands:
        - [ defvar, conf, '/files/etc/httpd/conf.d/owncloud.conf']
        - load 
        - [ defvar, ocloud_dir, '$conf/Directory[arg="/usr/share/owncloud/"]' ]
        - [ touch, '$ocloud_dir/directive[last()+1]' ]
        - [ defvar, last_stmt, '$ocloud_dir/directive[last()]']
        - [ set, '$last_stmt',  Require]
        - [ set, '$last_stmt/arg[1]', all ]
        - [ set, '$last_stmt/arg[2]', granted ]
        - save
        - [ match, '$last_stmt' ]
        # - [ match, '$last_stmt/[arg="moo"]' ]
        - [ augprint, '$conf//directive[.="Require" and arg="all" and arg="granted"]' ]
      augdebug: /tmp/aug1.log

  - name: Testing One-liner
    augeas: commands='set /files/etc/hosts/01/ipaddr 10.10.10.10' augdebug='/tmp/aug.log'

  - name: Testing Augeas lists 2
    augeas:
      commands:
        - [ defvar, conf, '/files/etc/httpd/conf.d/owncloud.conf']
        - [ defvar, ocloud_dir, '$conf/Directory[arg="/usr/share/owncloud/"]' ]
        # - [ augprint, '$ocloud_dir/[arg="all"]' ]
        - [ augprint, '$ocloud_dir' ]
      augdebug: /tmp/aug2.log

##DISABLE  - name: Testing Foo lists
##DISABLE    augeas:
##DISABLE      commands:
##DISABLE        - 1
##DISABLE        - 2
##DISABLE        - 3
##DISABLE      augdebug: /tmp/aug.log
##DISABLE
##DISABLE
