---

- hosts: all
  sudo: yes
  tasks:
  - name: Install packages
    yum: name={{ item }} state=present
    with_items:
    - httpd
    - php
    - owncloud
    - mariadb-server 
    - php-mysql
    - owncloud-mysql
    - iptables-services
    # we need below for ansible script, really
    - system-config-firewall-tui
    - MySQL-python
    - mod_ssl
    # we will need this for apache config manipulation
    - augeas
    - python-augeas
    # because we'll be pulling modules from Github
    - git

  - name: Enable services
    service: name={{ item }} state=started enabled=yes
    with_items:
    - httpd
    - mariadb
    - iptables

  - name: open up ports
    command: lokkit --service={{ item }}
    with_items:
    - http
    - https
    - ssh

  - name: Tune SELinux
    seboolean: name={{ item }} state=yes persistent=yes
    with_items:
    - httpd_can_network_relay
    - httpd_can_network_connect

  - name: create DB
    mysql_db: name={{ db_name }} state=present

  - name: create DB user
    mysql_user: name={{ db_username }}  password={{ db_password }} priv={{ db_name }}.*:ALL state=present

  - name: Add VHost
    template: src=templates/httpd_vhost.conf.j2 dest=/etc/httpd/conf.d/owncloud_vhost.conf mode=0644 backup=yes
    notify: httpd restart

  ## reconfigure apache: 
  ## 1. remove blanket include (?)
  ## 2. 
  ## - name: reconfigure httpd

  - name: Setup OwnCloud
    template: src=templates/owncloud-config.php.j2 dest=/etc/owncloud/config.php mode=0644 backup=yes

  # - name: Enable external access to owncloud
  #  script: httpd_enable_pub_owncloud

  - name: Check public access to owncloud
    augeas: commands='match $conf//directive[.="Require" and arg="all" and arg="granted"]' augdebug="/tmp/check.log"
    when: public_facing == "true"
    register: require_all_granted

  - name: Enable external access to owncloud
    augeas:
      backup: yes
      commands:
        - [ defvar, conf, '/files/etc/httpd/conf.d/owncloud.conf']
        - load 
        - [ defvar, ocloud_dir, '$conf/Directory[arg="/usr/share/owncloud/"]' ]
        - [ touch, '$ocloud_dir/directive[last()+1]' ]
        - [ defvar, last_stmt, '$ocloud_dir/directive[last()]']
        - [ set, '$last_stmt',  Require]
        - [ set, '$last_stmt/arg[1]', all ]
        - [ set, '$last_stmt/arg[2]', granted ]
        - save
    when: public_facing == "true"
    notify: httpd restart

  - name: Get Notes add-on
    git: repo=https://github.com/owncloud/notes.git dest=/var/www/owncloud/apps/notes
